### ISSUE TITLE
Form errors get cleared when combining superRefine with server-side mutation of form values

### ISSUE THREAD

**Issue by austerj** [ciscoheat/sveltekit-superforms#142] opened 2023-05-08 14:48 UTC
**Description**

Clearing / modifying values in the form on the server combined with `superRefine` leads to form errors being overwritten. In the MRE there are additional `password` and `confirmPassword` fields and the password matching is done in the schema with `superRefine`. A form error gets triggered from the server when `name === 'form'`.

The form error gets immediately cleared when both the password matching and clearing are enabled. When commenting out the password clearing, the form error displays as normal, and likewise when commenting out the `superRefine` - but having both at the same time seems to trigger an overwrite of the form error despite returning `setError` on the server and never modifying the form errors in the client code.

I'm speculating that some more general pattern is going on that mutates the errors at some stage between returning `setError` from the server and accessing `$errors._errors` on the client, but hopefully this really specific interaction can be a starting point!

Identified while dealing with https://github.com/ciscoheat/sveltekit-superforms/issues/141.

**MRE**

https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-6b62pq?file=src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment] 2023-05-22 13:44
This seems to be fixed now with v0.8.7, just released. #141 should be fixed too, can you please confirm @austerj?

**Comment by ciscoheat** [comment] 2023-05-25 08:29
I've made some more research, combined with #159, and it seems that `setError` and client-side validation aren't consistent with respect to one another:

**Using refine:** If you use refine on a schema, `_errors` will be populated, and checked for every validation:

```ts
export const schema = z.object({
  name: z.string().min(1)
})
.refine(data => data.name != 'Spam', 'You got spam');
```

**Using setError:** If you use `setError(form, null, message)` to set `_errors`, it won't be part of refine on the schema, and will be removed as soon as the client-side validation is executed.

I don't know how to solve this for both cases, and adding another option for persisting form-level errors makes things too complicated (there are enough validation options already as it is).

**Comment by ciscoheat** [comment] 2023-05-25 10:51
The problem is that it's not possible to detect whether the form-level error was created with refine or setError, they're both using `_errors` in the end. 

Which means that any `setError` will be removed upon client-side validation, since it's not a part of the schema, and the schema will report "no form-level errors" if refine isn't used or if returns no form-level errors.

**Comment by ciscoheat** [comment] 2023-05-25 11:40
Yes, it works since it's client-side as well. But `setError` cannot be, so it will be overwritten as soon as there is a client-side validation. 

I think I have to revert this behavior for the upcoming v1.0, possibly even removing the possibility to use `setError` for form-level errors.

**Comment by ciscoheat** [comment] 2023-05-26 18:49
From 1.0, setError cannot be used to set form-level errors, use refine/superRefine instead.

**Closed by ciscoheat** 2023-05-26 18:49 UTC
Labels: bug, next

**Comment by ciscoheat** [comment] 2023-05-26 20:47
You can use a [status message](https://superforms.vercel.app/concepts/messages#status-messages), it can be set to any type and will persist until next submit, unlike validation errors.
