### ISSUE TITLE
using pick on a valibot schema causes superforms to fail to submit when use:enhance is on.

### ISSUE THREAD

**Issue by delay** [ciscoheat/sveltekit-superforms#366] opened 2024-02-29 04:48 UTC
**Description**
When submitting a superform with valibot when use:enhance is active. Using a pick on valibot to select a partial schema causes submitting the form to fail with a 400 error.  If I make a new valibot schema with only the fields I am interested in, it works as expected.

Also another possible bug, when use:enhance is turned off $submitting also does not work on the form and is not being passed into the form on submit.  I don't know if that is expected behavior or not.

valibot-schemas.ts
```
import { string, email, object, boolean, minLength, toTrimmed, picklist, literal, date } from 'valibot';

const roleOptions = ['USER', 'PREMIUM', 'ADMIN'] as const;


export const userSchema = object({
	firstName: string([
		toTrimmed(),
		minLength(1, 'Please enter your first name.'),
	  ]),
	  lastName: string([
		toTrimmed(),
		minLength(1, 'Please enter your last name.'),
	  ]),
	email: string([
		toTrimmed(),
		email('The email address is not valid.'),
		minLength(1, 'An email address is required.'),
	  ]),
	  role: picklist(roleOptions, 'You must have a role.'),
	  verified: boolean(),
	  terms: literal(true, 'You must accept the terms and privacy policy.'),
	receiveEmail: boolean(),
	createdAt: date(),
	updatedAt: date()
}
);

export const emailSchema = object({
	email: string([
		toTrimmed(),
		email('The email address is not valid.'),
		minLength(1, 'An email address is required.'),
	  ]),
	});

export type UserSchema = typeof userSchema;
export type emailSchema = typeof emailSchema;
```
failing when using pick with a 400 error. It doesn't even try and hit the +page.server.ts
```
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Icons } from '$lib/components/icons';
	import { Button } from '$lib/components/ui/button';
	import * as Form from '$lib/components/ui/form';
	import { Input } from '$lib/components/ui/input';
	import { pick } from 'valibot';
	import { userSchema, emailSchema } from '$lib/config/valibot-schemas';
	import { valibotClient } from 'sveltekit-superforms/adapters';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';
	import SuperDebug from 'sveltekit-superforms';
	import * as Alert from '$lib/components/ui/alert';

	/const userAuthSchema = pick(userSchema, ['email']);

	type UserAuthSchema = typeof userAuthSchema;
	
	export let data: SuperValidated<Infer<UserAuthSchema>>;
	const form = superForm(data, {
		validators: valibotClient(userAuthSchema),
		dataType: 'json'
	});
	const { form: formData, submitting, message, enhance } = form;
	let isLoading = false;
</script>

<div class="lg:p-8">
	<div
		class="mx-auto flex w-full flex-col justify-center space-y-6 sm:w-[380px] border rounded-md p-8"
	>
		<div class="flex flex-col space-y-2 text-center">
			<h1 class="text-2xl font-semibold tracking-tight">Create an account</h1>
			<p class="text-sm text-muted-foreground">Enter your email below to create your account</p>
		</div>

		{#if $message?.status === 'success'}
			<Alert.Root variant="default">
				<Icons.userCreated class="h-4 w-4" />
				<Alert.Title>Account Created</Alert.Title>
				<Alert.Description>{$message.text}</Alert.Description>
			</Alert.Root>
		{:else}
			{#if $message}
				{#if $message?.status === 'error'}
					<Alert.Root variant="destructive">
						<Icons.warning class="h-4 w-4" />
						<Alert.Title>Error</Alert.Title>
						<Alert.Description>{$message.text}</Alert.Description>
					</Alert.Root>
				{/if}
			{/if}
			<form method="POST" use:enhance>
				<Form.Field {form} name="email">
					<Form.Control let:attrs>
						<Input
							{...attrs}
							bind:value={$formData.email}
							id="email"
							placeholder="name@example.com"
							type="email"
							autocapitalize="none"
							autocomplete="email"
							autocorrect="off"
							disabled={$submitting}
						/>
					</Form.Control>
					<Form.Description />
					<Form.FieldErrors class="w-full" />
				</Form.Field>
				<Form.Button disabled={$submitting} class="mt-2 w-full">
					{#if $submitting}
						<Icons.spinner class="mr-2 h-4 w-4 animate-spin" />
					{/if}
					Sign In with Email
				</Form.Button>
			</form>
			<span>{$submitting ? 'Logging in...' : 'Login'}</span>
			<SuperDebug data={form} />
		{/if}
	</div>
</div>
```

works fine if I make a separate schema with just the field I am interested in.
```
import { goto } from '$app/navigation';
	import { Icons } from '$lib/components/icons';
	import { Button } from '$lib/components/ui/button';
	import * as Form from '$lib/components/ui/form';
	import { Input } from '$lib/components/ui/input';
	import { pick } from 'valibot';
	import { emailSchema } from '$lib/config/valibot-schemas';
	import { valibotClient } from 'sveltekit-superforms/adapters';
	import { type SuperValidated, type Infer, superForm } from 'sveltekit-superforms';
	import SuperDebug from 'sveltekit-superforms';
	import * as Alert from '$lib/components/ui/alert';


	type EmailSchema = typeof emailSchema;
	export let data: SuperValidated<Infer<EmailSchema>>;

	const form = superForm(data, {
		validators: valibotClient(emailSchema),
		dataType: 'json'
	});
	const { form: formData, submitting, message, enhance } = form;
```

**Comment by ciscoheat** [comment] 2024-03-03 07:48
Can you reproduce it here? Then I'll take a closer look: https://stackblitz.com/edit/superforms-2-testing-valibot?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment] 2024-03-03 19:30
Couldn't reproduce it, but check if 2.7.0 fixes it anyway.

**Comment by ciscoheat** [comment] 2024-03-21 08:12
Closing, as Valibot has been updated and there have also been some improvements in its JSON Schema generator.

**Closed by ciscoheat** 2024-03-21 08:12 UTC
Labels: bug, question
