### ISSUE TITLE
onUpdated not trigged 

### ISSUE THREAD

**Issue by spidi123q** [ciscoheat/sveltekit-superforms#540] opened 2024-12-24 17:25 UTC
- [ ] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

I started my codebase with svelte 4 and following code worked fine for my client side validated form but after recent svelte 5 migration onUpdated no longer trigged but onUpdate is trigged.
Any help is appreciated 

package.json 
```
 "svelte": "^5.15.0"
"sveltekit-superforms": "^2.22.1",
"zod": "^3.23.8"
    "formsnap": "^1.0.1",
```

```
const form = superForm<any>(
    inboxAutomation
      ? {
          ...inboxAutomation,
        }
      : {
          name: "Untitled",
          messages_tree: {...InitialInboxAutomationMessageNode}
        },
    {
      SPA: true,
      resetForm: false,
      dataType: "json",
      validators: zodValidator(inboxAutomationSchema),
      onUpdated: async ({ form: f }) => {
        console.log("🚀 ~ onUpdated: ~ f:", f)
        if (f.valid) {
          try {
            //return submitAutomation(f.data);
          } catch (e) {
            console.log("error", e);
          }
        } else {
          console.log("form is invalid", f.errors);
         
          }
        }
      },
    },
  );
```

**Comment by ciscoheat** [comment] 2024-12-26 07:09
Duplicate of #536

**Closed by ciscoheat** 2024-12-26 07:09 UTC
Labels: bug
