### ISSUE TITLE
zod schema with "refine" results in type error

### ISSUE THREAD

**Issue by demetrius-mp** [ciscoheat/sveltekit-superforms#11] opened 2023-03-07 01:34 UTC
reproduction:
```ts
const schema = z
	.object({
		name: z.string(),
		email: z.string().email(),
		password: z.string().min(8),
		confirmPassword: z.string().min(8)
	})
	.refine((data) => data.password === data.confirmPassword, {
		message: "Passwords don't match",
		path: ['confirmPassword']
	});

export const load = (async (event) => {
	const form = await superValidate(event, schema);

	return {
		form
	};
}) satisfies PageServerLoad;
```

error:
Argument of type 'ZodEffects<ZodObject<{ name: ZodString; email: ZodString; password: ZodString; confirmPassword: ZodString; }, "strip", ZodTypeAny, { name: string; email: string; password: string; confirmPassword: string; }, { ...; }>, { ...; }, { ...; }>' is not assignable to parameter of type 'AnyZodObject'.
  Type 'ZodEffects<ZodObject<{ name: ZodString; email: ZodString; password: ZodString; confirmPassword: ZodString; }, "strip", ZodTypeAny, { name: string; email: string; password: string; confirmPassword: string; }, { ...; }>, { ...; }, { ...; }>' is missing the following properties from type 'ZodObject<any, any, any, { [x: string]: any; }, { [x: string]: any; }>': _cached, _getCached, shape, strict, and 14 more.ts(2345)

is this intentional?

**Comment by amorfati254** [comment] 2023-03-07 03:54
Yeah, experiencing same issue.

**Comment by ciscoheat** [comment] 2023-03-07 10:08
Thank you for reporting, I haven't considered using `ZodEffects` on the whole object, that's why it fails. I have to investigate if the type inference can handle extracting the `ZodObject` from the `ZodEffects` and still be compatible with the `Validation<T>` type.

In the meantime, I'd instead use `setError` to handle your case:

```ts
import { setError, superValidate } from 'sveltekit-superforms'

export const load = (async (event) => {
  const form = await superValidate(event, schema);

  if(form.data.password !== form.data.confirmPassword) {
    return setError(form, 'confirmPassword', "Passwords don't match");
  }

  return { form };
}) satisfies PageServerLoad;
```

**Comment by demetrius-mp** [comment] 2023-03-07 12:01
thanks so much for the quick response! loving this package

**Comment by ciscoheat** [comment] 2023-03-07 12:55
Glad to hear that :) I just noticed that the `setError` check should of course be in the form action, not in the load function.

**Comment by lnfel** [comment] 2023-03-16 14:22
+1 this enhancement

**Comment by ciscoheat** [comment] 2023-03-16 23:13
This is gonna work in the next release, in a few days.

**Comment by ciscoheat** [comment] 2023-03-19 22:57
Released now in v0.6, check out the announcement: https://github.com/ciscoheat/sveltekit-superforms/discussions/41

**Comment by demetrius-mp** [comment] 2023-03-21 13:59
im a bit out of time to test, if anyone already tested, this issue may be closed

**Comment by ciscoheat** [comment] 2023-03-21 14:00
I've done a couple of tests on separate installations, it works fine for me, but it can stay open for a little while longer.

**Comment by lnfel** [comment] 2023-03-22 06:07
I'll do some test after I've done some of my tasks at hand.

**Comment by JonaVDM** [comment] 2023-03-26 12:45
While it no longer gives an error, it doesn't seem to be working as intended. Now, whenever I open a page that has validation with `refine`, it appears to run the validation before the user has a chance to input anything.

Here is a example of it, commenting out `refine` doesn't show the validation errors in the form.
https://stackblitz.com/edit/sveltekit-superform-refine-error?file=src%2Froutes%2F%2Bpage.server.js,src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment] 2023-03-26 15:31
That's true, when there is no data sent to `superValidate`, as in a load function where `event` has no form data, or when you just pass `null/undefined` to it (which is essentially the same), there should be no errors displayed, as you most of the time don't want errors displayed on a freshly loaded form, only when the user starts to interact with it.

I will fix this for the next release in a day or two. As a workaround for now, use the `noErrors` option in the load function:

```ts
const form = await superValidate(event, schema, {noErrors: true});
```

**Comment by ciscoheat** [comment] 2023-03-26 22:19
Should be fixed now with v0.6.4.

**Comment by ciscoheat** [comment] 2023-04-04 03:18
Closing this, as the tests are working fine.

**Closed by ciscoheat** 2023-04-04 03:18 UTC
Labels: enhancement, done

**Comment by esafak** [comment] 2023-09-18 18:59
I still have this problem with 1.6.1 and zod 3.22.2:

> <html>Svelte: Type '{ form: SuperForm&lt;ZodObject&lt;{ email: ZodString; userName: ZodString; password: ZodString; passwordConfirm: ZodString; }, &quot;strip&quot;, ZodTypeAny, { ...; }, { ...; }&gt;, any&gt;; schema: ZodEffects&lt;...&gt;; }' is not assignable to type 'Form&lt;AnyZodObject&gt;'.<br/>Types of property 'schema' are incompatible.<br/>Type 'ZodEffects&lt;ZodObject&lt;{ email: ZodString; userName: ZodString; password: ZodString; passwordConfirm: ZodString; }, &quot;strip&quot;, ZodTypeAny, { ...; }, { ...; }&gt;, { ...; }, { ...; }&gt;' is missing the following properties from type 'ZodObject&lt;any, any, any, { [x: string]: any; }, { [x: string]: any; }&gt;': _cached, _getCached, shape, strict, and 14 more.
