### ISSUE TITLE
`$message` stays undefined on subsequent submission errors

### ISSUE THREAD

**Issue by f-elix** [ciscoheat/sveltekit-superforms#544] opened 2024-12-27 23:49 UTC
- [ ] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
When using the `message` helper to return an error with a status code of 400 and above, the `$message` store is set on the first submission. On subsequent submissions, the store is cleared but it is never set to the returned message value again.

Repro here: https://www.sveltelab.dev/uvboaqr0th4q102. You can try submitting the form multiple times, and the message never reappears. Note that a 200 works fine.

**Comment by ciscoheat** [comment] 2024-12-28 02:16
Probably a duplicate of #536, read there for a workaround, or reopen if not related.

**Closed by ciscoheat** 2024-12-28 02:16 UTC
Labels: bug
