### ISSUE TITLE
applyAction broken in V2 when attempting to redirect

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#329] opened 2024-02-07 23:49 UTC
When applyAction is set to `true`, and form action is a redirect on the backend, I am getting the error `ReferenceError: Cannot access 'unsub' before initialization`

**Comment by ciscoheat** [comment] 2024-02-08 05:28
I can't seem to reproduce this with a simple form action:

```ts
export const actions = {
  default: async () => {
    throw redirect(303, '/');
  }
};
```

Both with and without `use:enhance` on the form. Anything extra you do?

**Comment by saturnonearth** [comment] 2024-02-08 05:36
> I can't seem to reproduce this with a simple form action:
> 
> ```ts
> export const actions = {
>   default: async () => {
>     throw redirect(303, '/');
>   }
> };
> ```
> 
> Both with and without `use:enhance` on the form. Anything extra you do?

Oops I meant to say ...When applyAction is set to `false`, also, with SvelteKit 2 the redirect is automatically thrown without explicitly "throwing". (not sure if you are using SK2 in the test)

**Comment by ciscoheat** [comment] 2024-02-08 07:26
Will be fixed in the next alpha version. Thanks. :)

**Comment by ciscoheat** [comment] 2024-02-08 07:28
Just note that it won't do the actual redirect, since applyAction is false. But that was expected, right?

**Comment by alanxp** [comment] 2024-02-09 04:59
> Should be working now with alpha.47

will it be fixed in v1 ? It also happens in v1 with sveltekit 2.

**Comment by ciscoheat** [comment] 2024-02-09 05:26
It will eventually, but I'm focusing on the v2 release right now.

**Comment by alanxp** [comment] 2024-02-09 06:26
> Should be working now with alpha.47

Still not working with alpha .49

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/15839818/e01ac05a-40e0-440f-b7ee-22a5cc87507d)

+page.server.ts

![image](https://github.com/ciscoheat/sveltekit-superforms/assets/15839818/7c44e2f7-4dbf-430f-947d-71c26a1c3f55)

**Comment by ciscoheat** [comment] 2024-02-09 06:35
Are you sure the library version has updated? That redirect works in the test suite. Try to restart the IDE, and if it persists, make a reproducible here, and I'll take a look: https://stackblitz.com/edit/superforms-2-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by saturnonearth** [comment] 2024-02-09 16:39
> Should be working now with alpha.47

Fixed! Many thanks

**Closed** 2024-02-09 16:47 UTC
Labels: bug, confirmed
