### ISSUE TITLE
Asynchronous client validation errors are deleted

### ISSUE THREAD

**Issue by rburgst** [ciscoheat/sveltekit-superforms#127] opened 2023-05-02 10:01 UTC
**Description**
As documented in https://superforms.vercel.app/concepts/client-validation#asynchronous-validation-and-debouncing you are supposed to add the async validation result to the `$errors.email` attribute. However, this does not work when doing client side validation.

Here is a repro sample
https://stackblitz.com/edit/sveltekit-superforms-testing-okzxe7?file=src/routes/+page.svelte

To check do the following:
1. enter `xxx@gmail.com` as an email, see that you get a validation error
2. Tab out of the field (e.g. focus the name field)

### Expected:
The validation error should still stay visible

### Actual
The validation error disappears as soon as you tab out of the field.

<img width="535" alt="grafik" src="https://user-images.githubusercontent.com/22971/235637665-28d5fd5e-a4e9-40a9-a8e0-3b67e98b3f7a.png">

**Comment by M4rk3tt0** [comment] 2023-05-02 12:13
You could just **refine** your schema, without all that custom validation that you were doing in the +page.svelte.

```
import { z } from 'zod';

export const schema = z.object({
	name: z.string().min(2),
	email: z
		.string()
		.email()
		.refine((val) => val !== 'xxx@gmail.com', {
			message: "Don't use this email"
		})
});
```

**Comment by ciscoheat** [comment] 2023-05-02 22:30
I see what you mean, will try to reproduce this locally and come up with a fix in the next patch version.

**Comment by ciscoheat** [comment] 2023-05-04 11:29
This turned out to be a bit complicated, since the `$error` assignment in `on:input` will clash with the `validators`. So the custom, throttled error will be added, but on blur the schema validator will kick in, find no error and remove it.

Refining the schema, as suggested by @M4rk3tt0 , works, but will delay the validation for **all** fields, since they will wait for the async operation to finish.

The solution I can see is to add an additional option field, `delayedValidators`, that will run after `validators`.

**Comment by rburgst** [comment] 2023-05-04 20:06
This is the approach that felte has taken. IMHO this makes a lot of sense. Actually IIRC felte does the throttling for you which is a neat twist.

**Comment by ciscoheat** [comment] 2023-05-04 20:12
There are plenty of throttle/debounce libraries, I'll leave it open which one to use, so the `delayedValidators` will just have to return a promise.

**Comment by ciscoheat** [comment] 2023-06-03 20:42
After plenty of experimentation, I have determined that there are too many scenarios for this to be feasible to handle with a general solution in Superforms (at least v1.0). I'll probably recommend that the field in question should be excluded from the schema and handled separately.

**Comment by ciscoheat** [comment] 2023-06-05 06:26
Closing this in preparation for 1.0.

**Closed by ciscoheat** 2023-06-05 06:26 UTC
Labels: enhancement, wontfix
