### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for '<field>' in <string>

### ISSUE THREAD

**Issue by dmoebius** [ciscoheat/sveltekit-superforms#161] opened 2023-05-25 18:17 UTC
**Description**
See MRE https://stackblitz.com/edit/sveltekit-superforms-testing-evgwd4
1. Click "Submit" -> validation error "Need at least two persons" is shown
2. Click "Add person"

Expected: new person input gets added

Actual:
```
sveltekit-superforms_client.js?v=e57f7f69:1089 Uncaught TypeError: Cannot use 'in' operator to search for 'name' in Need at least two persons
    at Tainted__validate (sveltekit-superforms_client.js?v=e57f7f69:1089:51)
    at Tainted_update (sveltekit-superforms_client.js?v=e57f7f69:1115:9)
    at Object.set (sveltekit-superforms_client.js?v=e57f7f69:974:9)
    at set_store_value (chunk-UJLIVLOQ.js?v=e57f7f69:150:9)
    at HTMLButtonElement.addPerson (+page.svelte:11:21)
    at HTMLButtonElement.<anonymous> (chunk-UJLIVLOQ.js?v=e57f7f69:374:15)
```

**MRE**
https://stackblitz.com/edit/sveltekit-superforms-testing-evgwd4

**Comment by dmoebius** [comment] 2023-05-25 18:23
The problem seems to be that the zod schema sets a custom error on path 'persons'. Superforms somehow fails to validate this path during `Tainted_update`.

**Comment by ciscoheat** [comment] 2023-05-26 13:55
This is a tricky issue that will be documented in the upcoming 1.0 release. Adding errors to objects or arrays in the schema isn't really supported, as you did with `persons` (which is an array), and will cause problematic behavior like you experience. 

The problem is that you can't really prevent this though, Zod doesn't stop you from adding errors to any path, but it doesn't work with Superforms, that only supports errors for leafs in the schema, if you look at it as a tree structure.

However, you can add form-level errors in almost the same manner, here's a working version of your MRE: https://stackblitz.com/edit/sveltekit-superforms-testing-mpvand?file=src%2Froutes%2F%2Bpage.svelte,src%2Flib%2Fschema.ts

- The refine method adds a form-level message (no path), which is used on the page as `$errors._errors`.
- Since you are using nested data, you need `dataType: 'json'`
- You probably don't want to taint the fields when adding a person, so `addPerson` has been modified to handle that.

**Comment by ciscoheat** [comment] 2023-06-08 11:09
This is related to array-level errors, which is added now in 1.0.0-rc.3, so I'm closing this since the 1.0 release is very close.

**Closed by ciscoheat** 2023-06-08 11:09 UTC
Labels: documentation
