### ISSUE TITLE
Does not allow to chain regex

### ISSUE THREAD

**Issue by jKm00** [ciscoheat/sveltekit-superforms#150] opened 2023-05-14 17:16 UTC
**Description**
Zod allows for chaining regex, but when used with superforms it gives the error: "Only one regex is allowed per field".

**If applicable, a MRE**
https://stackblitz.com/edit/sveltekit-superforms-bug-reporting-tphkb6?file=src/routes/+page.server.ts

**Comment by ciscoheat** [comment] 2023-05-14 17:54
This is because the constraints only allows one regexp value, so the mapping will fail otherwise, but in 1.0 it will be possible with a warning, that can be turned off.

**Comment by ciscoheat** [comment] 2023-05-19 23:56
Closed as a duplicate of #115

**Comment by ciscoheat** [comment] 2023-05-19 23:57
Opening again, until 1.0 is released!

**Closed** 2023-05-30 19:12 UTC
Labels: duplicate, enhancement, done
