### ISSUE TITLE
When I build, I am getting a Circular Dependency warning.  

### ISSUE THREAD

**Issue by delay** [ciscoheat/sveltekit-superforms#365] opened 2024-02-27 22:21 UTC
When I do an `npm run build` I am getting a Circular Dependency warning.  It seems to work fine but it gives me this error warning.  I am using valibot for the schema validation.

```
import type { PageServerLoad, Actions } from "./$types";
import { fail, redirect } from "@sveltejs/kit";
import { superValidate, setError } from "sveltekit-superforms";
import { valibot } from "sveltekit-superforms/adapters";
import { userSchema } from '$lib/config/valibot-schemas';
import { pick } from 'valibot';
import { lucia } from '$lib/server/lucia';
import { setFlash } from 'sveltekit-flash-message/server';
import { createUser } from '$lib/server/database/user-model';
import { sendMagicLinkEmail } from '$lib/config/email-messages';

const userAuthSchema = pick(userSchema, ['email']);

export const load: PageServerLoad = async (event) => {
    if (event.locals.user) {
		redirect(302, '/dashboard');
	}
  return {
    form: await superValidate(valibot(userAuthSchema)),
  };
};
 
export const actions: Actions = {
  default: async (event) => {
    const form = await superValidate(event, valibot(userAuthSchema));
    console.log('form: ', JSON.stringify(form));
    if (!form.valid) {
      return fail(400, {
        form,
      });
    }
```
**Description**
error messages when running npm run build.
`Export "superValidate" of module "node_modules/sveltekit-superforms/dist/superValidate.js" was reexported through module "node_modules/sveltekit-superforms/dist/index.js" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.`

**Comment by ciscoheat** [comment] 2024-02-28 07:08
I'll take a look at the exports, it should work without problem at least.

**Comment by ciscoheat** [comment] 2024-03-03 19:30
Couldn't reproduce it, but I changed some imports, so take a look and see if it's still there with 2.7.0.

**Comment by Anthony-Mariotti** [comment] 2024-03-10 20:24
As I was digging around, because I stumbled across the same issue and was receiving the same error on build. I know this won't be the solution to everyone, but  I was previously on `v2.6.2` then updated to `v2.8.1` and the circular dependency issue vanished. 

pre-update of package:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/48564383/67aeda2e-10f2-48bd-850f-5a00284b21a5)

pnpm outdated:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/48564383/82027b6d-569e-4100-8099-7c2760e6790d)

after update:
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/48564383/25522127-6d5b-4ecd-8dd1-3818da6b3d2b)

**Comment by ciscoheat** [comment] 2024-03-11 15:18
Closing this, as I've done some import fixes between these versions. If you still have problems @delay, comment here and I'll reopen.

**Closed by ciscoheat** 2024-03-11 15:18 UTC
Labels: bug, question, next

**Comment by delay** [comment] 2024-03-24 23:27
I just wanted to let you know I updated to the latest version and no longer get this issue.  Thanks for the fix!!
