### ISSUE TITLE
Vine & other deps getting unnecessarily installed

### ISSUE THREAD

**Issue by o-az** [ciscoheat/sveltekit-superforms#413] opened 2024-04-22 17:46 UTC
- [x] Before posting an issue, read the [FAQ](https://superforms.rocks/faq) and search the previous issues.

**Description**
I noticed `@vinejs/vine` and other deps are being installed unnecessarily 

**If applicable, a MRE**
The [default `valibot` example you have](https://www.sveltelab.dev/?provider=github&owner=ciscoheat&repo=superforms-examples&branch=valibot). In the cli run
```sh
npm ls @vinejs/vine

ls node_modules/@vinejs/vine/build/
```
![CleanShot 2024-04-22 at 10 46 05](https://github.com/ciscoheat/sveltekit-superforms/assets/23618431/4eeb7c35-dabe-4513-9acd-39ab5c49a58b)

**Comment by ciscoheat** [comment] 2024-04-22 19:16
Duplicate of https://github.com/ciscoheat/sveltekit-superforms/issues/351

**Closed by ciscoheat** 2024-04-22 19:16 UTC
Labels: bug
