### ISSUE TITLE
Support new Valibot piping?

### ISSUE THREAD

**Issue by saturnonearth** [ciscoheat/sveltekit-superforms#432] opened 2024-05-21 00:34 UTC
Valibot just released the first RC (https://github.com/fabian-hiller/valibot/releases/tag/v0.31.0-rc.0) for their new piping functionality - is this compatible with Superforms?

**Comment by lumosminima** [comment] 2024-05-22 05:25
Don't think so (using `Svelte 5` and validbot `0.31.0-rc`)
![image](https://github.com/ciscoheat/sveltekit-superforms/assets/81504231/25940cfb-6642-4a61-ab32-10488c8cb0f1)

**Comment by ciscoheat** [comment] 2024-05-22 05:39
I installed it and ran the tests. It'll be quite a bit of work to make the tests pass, and probably a bit in https://github.com/gcornut/valibot-json-schema as well (the JSON Schema generator). Even more if we want to keep backwards compatibility.

**Comment by saturnonearth** [comment] 2024-05-22 13:50
> I installed it and ran the tests. It'll be quite a bit of work to make the tests pass, and probably a bit in https://github.com/gcornut/valibot-json-schema as well (the JSON Schema generator). Even more if we want to keep backwards compatibility.

I think since it's a library not even in 1.0, there is no need to keep backwards compatibility, imo

**Comment by slowsage** [comment] 2024-05-28 11:43
Draft PR #437 created. Version of `valibot-json-schema` and `valibot` not yet finalized in `package.json`:

- `valibot-json-schema`: Waiting on PR [#57](https://github.com/gcornut/valibot-json-schema/pull/57) in `valibot-json-schema` to be merged to update version number.

- `valibot`: Would appreciate thoughts on specifying `valibot@"^0.31.0-rc5"` - a release candidate.

**Comment by fabian-hiller** [comment] 2024-06-03 00:18
I am happy to help with any questions.

**Comment by ciscoheat** [comment] 2024-06-10 10:39
Updated to v0.31 and seems to be working fine with v2.15.0, can anyone confirm?

**Comment by sillvva** [comment] 2024-06-10 19:28
Everything (types, logic, etc.) seems to be working as expected in my app.

**Comment by saturnonearth** [comment] 2024-06-11 05:29
I am getting an error, and some type errors, but this could be because I am using the [Drizzle ](https://github.com/drizzle-team/drizzle-orm)to Valibot adapter which has yet to be updated. Although one error I am getting is...

```The "undefinedStrategy" option must be set to handle the `undefined` schema```

which seems to be coming from: [@gcornut+valibot-json-schema](https://github.com/gcornut/valibot-json-schema)

**Comment by sillvva** [comment] 2024-06-11 11:30
> I am getting an error, and some type errors, but this could be because I am using the [Drizzle ](https://github.com/drizzle-team/drizzle-orm)to Valibot adapter which has yet to be updated. Although one error I am getting is...
> 
> ```The "undefinedStrategy" option must be set to handle the `undefined` schema```
> 
> which seems to be coming from: [@gcornut+valibot-json-schema](https://github.com/gcornut/valibot-json-schema)

The creator of valibot, Fabian, is working with the Drizzle team to update it. I'd wait for that before migrating.

https://discord.com/channels/1043890932593987624/1083702388021538816/1247145749817593917

**Comment by fabian-hiller** [comment] 2024-06-11 11:36
Here is the Drizzle PR: https://github.com/drizzle-team/drizzle-orm/pull/2481

**Comment by saturnonearth** [comment] 2024-06-11 17:49
> > I am getting an error, and some type errors, but this could be because I am using the [Drizzle ](https://github.com/drizzle-team/drizzle-orm)to Valibot adapter which has yet to be updated. Although one error I am getting is...
> > `` The "undefinedStrategy" option must be set to handle the `undefined` schema ``
> > which seems to be coming from: [@gcornut+valibot-json-schema](https://github.com/gcornut/valibot-json-schema)
> 
> The creator of valibot, Fabian, is working with the Drizzle team to update it. I'd wait for that before migrating.
> 
> https://discord.com/channels/1043890932593987624/1083702388021538816/1247145749817593917

Awesome!!

**Comment by ciscoheat** [comment] 2024-06-12 07:34
@saturnonearth You may have to configure the adapter with `undefinedStrategy` set, as it's hard to know your intention for that validation.

**Comment by shiftlabs1** [comment] 2024-06-12 11:12
> > Updated to v0.31 and seems to be working fine with v2.15.0, can anyone confirm?
> 
> unknow() does not work . I get the error
> 
> ```
> Error: Unsupported valibot schema: unknown
> ```
> 
> using latest schema definition for example
> 
> ```
> 	netMonthlyPay: pipe(unknown(), transform(Number)),
> 	grossMonthlyPay: pipe(unknown(), transform(Number)),
> ```
> 
> used to before the upgrade .
> 
> I see the error may be coming from valibot-json-schema , i guess the flag ignoreUnknownValidation needs to be set somewhere ?

Update:  This has been replaced (in valibot ) with the union and transform type , so as not to convert unknown to a defined type

**Comment by shiftlabs1** [comment] 2024-06-12 11:43
> > > Updated to v0.31 and seems to be working fine with v2.15.0, can anyone confirm?
> > 
> > 
> > unknow() does not work . I get the error
> > ```
> > Error: Unsupported valibot schema: unknown
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > using latest schema definition for example
> > ```
> > 	netMonthlyPay: pipe(unknown(), transform(Number)),
> > 	grossMonthlyPay: pipe(unknown(), transform(Number)),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > used to before the upgrade .
> > I see the error may be coming from valibot-json-schema , i guess the flag ignoreUnknownValidation needs to be set somewhere ?
> 
> Update: This has been replaced (in valibot ) with the union and transform type , so as not to convert unknown to a defined type

Now getting Multi-type unions must have a default value, or exactly one of the union types must have.
error

**Comment by saturnonearth** [comment] 2024-06-12 13:49
> @saturnonearth You may have to configure the adapter with `undefinedStrategy` set, as it's hard to know your intention for that validation.

I am not sure what you mean - as I haven't set anything up with `undefinedStrategy` validations - is likely coming from the drizzle adapter.

**Comment by sillvva** [comment] 2024-06-25 02:46
@fabian-hiller It looks like something in Valibot between 0.32.0 (working) and 0.33.3 (not working) broke it again. It seems like the `GenericSchema` types between these two versions are not compatible.

When I pass this schema to `valibot()`
```ts
export const newCharacterSchema = v.object({
	name: requiredString,
	campaign: v.optional(v.pipe(v.string(), maxStringSize), ""),
	race: v.optional(v.pipe(v.string(), maxStringSize), ""),
	class: v.optional(v.pipe(v.string(), maxStringSize), ""),
	characterSheetUrl: optionalURL,
	imageUrl: optionalURL
});
```
Like this: 
```ts
const form = await superValidate(
	parent.character
		? {
				name: parent.character.name,
				campaign: parent.character.campaign || "",
				race: parent.character.race || "",
				class: parent.character.class || "",
				characterSheetUrl: parent.character.characterSheetUrl || "",
				imageUrl: parent.character.imageUrl.replace(BLANK_CHARACTER, "")
			}
		: undefined,
	valibot(newCharacterSchema),
	{
		errors: false
	}
);
```
I get this error:
```
Argument of type 

'ObjectSchema<{ readonly name: SchemaWithPipe<[StringSchema<undefined>, MinLengthAction<string, 1, string>]>; readonly campaign: OptionalSchema<SchemaWithPipe<[StringSchema<undefined>, MaxLengthAction<string, 255, string>]>, "">; readonly race: OptionalSchema<SchemaWithPipe<[StringSchema<undefined>, MaxLengthAction<string, 255, string>]>, "">; readonly class: OptionalSchema<SchemaWithPipe<[StringSchema<undefined>, MaxLengthAction<string, 255, string>]>, "">; readonly characterSheetUrl: OptionalSchema<SchemaWithFallback<SchemaWithPipe<[StringSchema<undefined>, UrlAction<string, undefined>, MaxLengthAction<string, 255, string>]>, "">, "">; readonly imageUrl: OptionalSchema<SchemaWithFallback<SchemaWithPipe<[StringSchema<undefined>, UrlAction<string, undefined>, MaxLengthAction<string, 255, string>]>, "">, "">; }, undefined>' 

is not assignable to parameter of type 'SupportedSchemas'.
```
Where `SupportedSchemas` is `GenericSchema | GenericSchemaAsync`

The above type _is_ compatible with the `GenericSchema` type in version 0.33.3, but not in the version installed by `sveltekit-superforms` (0.31.x)

**Comment by fabian-hiller** [comment] 2024-06-25 09:30
This is strange because I haven't made any changes to `BaseSchema`, `BaseSchemaAsync`, `GenericSchema` and `GenericSchemaAsync` since v0.31.0.

**Comment by sillvva** [comment] 2024-06-25 12:21
Here's a MRE of the issue
https://stackblitz.com/edit/stackblitz-starters-whs5op?file=index.ts

And here's the MRE where it's working with Valibot 0.32.0
https://stackblitz.com/edit/stackblitz-starters-6zducd?file=index.ts

The version of Superforms is unchanged between these MREs.

**Comment by fabian-hiller** [comment] 2024-06-25 12:42
I think I know what the problem is. I have changed some types that are part of the `BaseIssue` type which probably causes this problem. I recommend upgrading Valibot in Superforms to the latest version and see if this fixes the problem. Thanks for reporting this!

**Comment by ciscoheat** [comment] 2024-06-26 05:49
See if it works now with 2.15.2

**Comment by sillvva** [comment] 2024-06-26 12:24
> See if it works now with 2.15.2

Resolved

**Closed** 2024-07-09 23:09 UTC
Labels: bug, done
