### ISSUE TITLE
valibot support

### ISSUE THREAD

**Issue by Suyashtnt** [ciscoheat/sveltekit-superforms#244] opened 2023-08-04 17:43 UTC
**Is your feature request related to a problem? Please describe.**
Not really related to a problem, just seems like a cool idea to add support for https://valibot.dev, as it seems to be a really good competitor to zod, especially in bundle size while stilling having a neat api

**Describe the solution you'd like**
A way to support valibot or even maybe a way to create custom adapters.

**Describe alternatives you've considered**
The clear alternative is to just use zod, which I currently am.

**Additional context**
Seems that valibot has a similar API to zod

**Comment by ciscoheat** [comment] 2023-08-04 18:15
Duplicate of #120 , that also describes why it's problematic. I've mentioned it to the Valibot author as well, he confirmed that it doesn't fulfill the requirements yet.

**Closed by ciscoheat** 2023-08-04 18:15 UTC
Labels: enhancement
