### ISSUE TITLE
Add a `submit()` function to the response of superForm()

### ISSUE THREAD

**Issue by fell-lucas** [ciscoheat/sveltekit-superforms#126] opened 2023-05-01 13:18 UTC
**Is your feature request related to a problem? Please describe.**
When using a `Dialog` from https://svelte-headlessui.goss.io/docs/dialog to confirm the submitting of the form, the submit button does not work because the `Dialog` is rendered at the root of the page, to provide better accessibility. With this, the `button` element stops being a child of the `form` element, not allowing the form to be submitted.

**Describe the solution you'd like**
I think a `submit()` function would be helpful in this scenario, so we can call it in the `on:click` of the submit `button` inside the `Dialog`.

**Describe alternatives you've considered**
Currently I've tried binding the `form` element to a variable and calling `form.submit()` in a handler function. However, I'm not sure how to `preventDefault()` in this case, so the page always refreshes when submitting.

Edit: a new workaround I've found that works but is questionable... Is to create a hidden submit button inside the form and bind it to a variable. Then call `button.click()` from the `Dialog` button, while also closing the Dialog on:click.

**Comment by ryoppippi** [comment] 2023-05-01 13:51
duplicate of #75

**Closed** 2023-05-01 13:56 UTC
Labels: enhancement
