### ISSUE TITLE
Issue with input type "number", and "datetime-local" when using proxy objects for optionality.

### ISSUE THREAD

**Issue by Jabronironi** [ciscoheat/sveltekit-superforms#232] opened 2023-07-17 17:17 UTC
When you want to apply validation rules with optionality, it appears the approach is to use proxy objects.  During my testing, I noticed some issues with some of the input types when doing this.  I have created a quick repo to reproduce these issues:

https://github.com/Jabronironi/SuperFormsNumberProxyIssue

- When you use "number" input type, the taint and validation rules do not fire properly (form will be valid when it isn't, form won't taint on change).
- When you use "datetime-local" input type, the validation does not fire on blur (however, it appears the taint event does fire).
- If you use "text" input type, these issues go away, but you lose some of the browser specific field benefits.

**Comment by ciscoheat** [comment] 2023-07-17 18:11
Thank you, will take a look soon! Just to clarify, when you say taint event, do you mean that the $tainted store is updated?

**Comment by Jabronironi** [comment] 2023-07-18 00:22
No problem.  Yes, the store does not indicate tainted after you change the "number" value.  For datetime-local, the store does update saying it is tainted, but the validation rule does not fire (like it does normally).

**Comment by ciscoheat** [comment] 2023-07-18 10:31
There seems to be no subdirectories committed in the repo?

**Comment by Jabronironi** [comment] 2023-07-18 13:40
Dang it.  Sorry, not sure what I did there.  Just updated the repo with the missing directories.

**Comment by ciscoheat** [comment] 2023-07-18 16:19
The datetime fix will be included in the next release.

**Comment by ciscoheat** [comment] 2023-07-18 16:29
I may have found an issue with the number proxy too, since you were specifying the empty option.

**Comment by ciscoheat** [comment] 2023-07-20 12:37
> I just tested with input type "number" while binding to a number | undefined form type. Once you enter an invalid value, then clear it and blur the field, the validation still shows "invalid", even though the zod definition is "optional". That feels like an incorrect behavior.

Check if this is fixed now in 1.4.0.

**Comment by Jabronironi** [comment] 2023-07-20 18:00
This is still not working.  To make sure we are on same page - I am not using a number proxy here (I think you mentioned that was not needed for numbers as Svelte handles that conversion step).  If I enter an invalid number and blur - validation fires.  If I refocus and clear the field and blur, the validation does not clear and the form still shows as invalid.

**Comment by Jabronironi** [comment] 2023-07-20 18:09
@ciscoheat  However - datetime is working better.  The issue just remains on empty option for number.  See previous comment.

**Comment by ciscoheat** [comment] 2023-07-20 18:26
It sounds like a simple thing, so please make an MRE here and I'll take a look: https://stackblitz.com/edit/sveltekit-superforms-1-testing?file=src%2Froutes%2F%2Bpage.server.ts,src%2Froutes%2F%2Bpage.svelte

**Comment by ciscoheat** [comment] 2023-07-21 14:12
When using input type="number" and no proxy, I can't reproduce this. The closest I can get is to have an empty field value, which Svelte binds to `null`, so an `optional()` schema field will trigger a validation error, but it will be removed (and added again) when changing values.

Using nullable/nullish instead of optional works fine.

**Comment by Jabronironi** [comment] 2023-07-21 19:46
Okay, I just tested in stackblitz - and it worked.  You can close this.  Thank you!  I will figure out what is going on in my local project and open a new issue if I still find an issue. But for now, I think this appears to be working as expected.

**Closed** 2023-07-21 20:26 UTC
Labels: bug, next, confirmed

**Comment by Jabronironi** [comment] 2023-07-22 16:02
Okay, one last check here.  I thought it was working when I did it in stackblitz, tried to do it in my project, no luck.  So tried to recreate in stackblitz (deleted my previous fork), and now I am getting the bad behavior.  

See: https://stackblitz.com/edit/sveltekit-superforms-1-testing-quddkj?file=src%2Froutes%2F%2Bpage.svelte

If I enter 100 and blur, invalid(expected behavior).  When I clear field and blur, invalid saying number expected (not expected behavior).  What am I doing wrong here?
